services:
  ubuntu-setup:
    container_name: php8_full
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "80:80"
      - "5432:5432"
    volumes:
      - /home/doncho/careye:/home/app/src
      - db:/var/lib/postgresql/13/main
    restart: unless-stopped
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
volumes:
  db:
    external: true